apiVersion: v1
kind: ConfigMap
metadata:
  name: idmatr-config
  namespace: idmatr
data:
  NODE_ENV: "production"
  DEMO_MODE: "false"
  NATS_URL: "nats://nats:4222"
  REDIS_URL: "redis://redis:6379"
  NEO4J_URL: "bolt://neo4j:7687"
  NEO4J_USER: "neo4j"
  POSTGRES_USER: "idmatr"
  POSTGRES_DB: "idmatr_db"
  ALLOWED_ORIGINS: "http://localhost:3000"
  SMTP_PORT: "587"
